<?php

namespace Fairplay\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends EntityRepository
{
    public function findByDistrict($id)
    {
        $query = $this->getEntityManager()
                ->createQuery('
                SELECT s from FairplayMainBundle:Stadium s where s.district = :id')
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function updateRating($id, $score)
    {
        $em=$this->getEntityManager();
        $stadium = $em->getRepository('FairplayMainBundle:Stadium')->find($id);
        $oldScore = $stadium->getScore();
        $oldAmount = $stadium->getAmount();
        $newScore = ($oldAmount*$oldScore+$score)/($oldAmount+1.0);
        $stadium->setScore($newScore);
        $stadium->setAmount($oldAmount+1.0);
        $em->flush();
        return array("score"=>$newScore, "amount"=>$oldAmount+1,'id'=>$id);
    }
}
