<?php

namespace Fairplay\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends EntityRepository
{
    public function findByDistrict($id)
    {
        $query = $this->getEntityManager()
                ->createQuery('
                SELECT s from FairplayMainBundle:Stadium s where s.district = :id')
            ->setParameter('id',$id);
        return $query->getResult();
    }
}
