fairplay_main_homepage:
    pattern:  /
    defaults: { _controller: FairplayMainBundle:Main:index }

fairplay_main_search:
    pattern: /district/{id}/
    defaults: { _controller: FairplayMainBundle:Stadium:search }

fairplay_ajax_rating:
    pattern: /update/stadium/{id}/rating/{score}/
    defaults: { _controller: FairplayMainBundle:Ajax:rating }
    options:
        expose: true

fairplay_stadium_info:
    pattern: /stadium/{id}/
    defaults: { _controller: FairplayMainBundle:Stadium:info }
    requirements:
      id: \d+

fairplay_calendar_event:
      pattern: /stadium/{id}/event/
      defaults: { _controller: FairplayMainBundle:Ajax:loadEvent }
      requirements:
        id: \d+
      options:
          expose: true

fairplay_ajax_event_select:
      pattern: /reserve/stadium/{id}/event/create/
      defaults: { _controller: FairplayMainBundle:Event:createEvent }
      requirements:
        id: \d+
      options:
          expose: true